version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
    - 7.25.0
  - dependency-name: "@tryghost/helpers"
    versions:
    - 1.1.38
    - 1.1.39
    - 1.1.40
    - 1.1.41
    - 1.1.43
  - dependency-name: gatsby-image
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
  - dependency-name: gatsby
    versions:
    - 2.32.10
    - 2.32.11
    - 2.32.12
    - 2.32.2
    - 2.32.3
    - 2.32.4
    - 2.32.6
    - 2.32.8
    - 2.32.9
  - dependency-name: "@tryghost/helpers-gatsby"
    versions:
    - 1.0.43
    - 1.0.44
    - 1.0.45
    - 1.0.46
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.0
    - 7.23.1
    - 7.23.2
  - dependency-name: gatsby-transformer-sharp
    versions:
    - 2.12.1
  - dependency-name: gatsby-plugin-sharp
    versions:
    - 2.14.1
    - 2.14.2
    - 2.14.3
  - dependency-name: gatsby-plugin-feed
    versions:
    - 2.13.1
  - dependency-name: gatsby-source-filesystem
    versions:
    - 2.11.1
  - dependency-name: gatsby-plugin-offline
    versions:
    - 3.10.1
    - 3.10.2
  - dependency-name: gatsby-plugin-manifest
    versions:
    - 2.12.1
  - dependency-name: lodash
    versions:
    - 4.17.21
